### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by NotSqrt** [gluster/libgfapi-python#9] opened 2015-09-17 09:50 UTC
Hello,

In case you want to look at a working branch in py33/34, have a look at https://github.com/NotSqrt/libgfapi-python/tree/python3-support

I assume it's not mergeable as is, you'll want to follow your workflow.

I started from the work of @asivokon

Regards

**Comment by bmabey** [comment] 2018-01-22 22:32
It looks like `master` has now drifted since this work was done. Does anyone plan on adding python 3 support soon to this library?

**Comment by bmabey** [comment] 2018-01-24 23:13
@prashanthpai Is pyhton 3.0 support on the roadmap? Also, would you be willing to merge in a PR that added support? (I'm not sure why this work was never merged in the first place.)

**Comment by prashanthpai** [comment] 2018-01-25 03:52
@bmabey Yes it is on the roadmap. I haven't had the time to work on it though.

Unfortunately, this GitHub repo is a read-only mirror and we do not follow the PR model for contributions.  Patches to add Python 3 support would be great  and are most welcome as long as it doesn't cause regressions in Python 2 support. We use [Gerrit](https://review.gluster.org/#/q/project:libgfapi-python) for [accepting code contributions](https://github.com/gluster/libgfapi-python/blob/master/doc/markdown/dev_guide.md) and reviewing.

Cheers :)

**Comment by eLvErDe** [comment] 2018-04-24 13:54
I did it here:
https://github.com/gluster/libgfapi-python/pull/21

**Comment by prashanthpai** [comment] 2018-09-21 05:57
Merged in https://github.com/gluster/libgfapi-python/commit/d5e4a0362a08ca3c0e7a33ea8caafccb22b906b2 and available in [release 1.2](https://github.com/gluster/libgfapi-python/releases/tag/v1.2)

**Closed** 2018-09-21 05:58 UTC
Labels: enhancement
